return {
  'mfussenegger/nvim-dap',
  dependencies = {
    'nvim-neotest/nvim-nio',
    'rcarriga/nvim-dap-ui',
    'nvim-telescope/telescope-dap.nvim',
  },
  config = function()
    local dap = require 'dap'
    local ui = require 'dapui'

    local ok, telescope = pcall(require, 'telescope')
    if ok then
      telescope.load_extension 'dap'
    end

    require('dapui').setup()

    -- 1. Define the Adapter (How Neovim connects to the debugger)
    dap.adapters.gdb = {
      type = 'executable',
      command = 'arm-none-eabi-gdb',
      args = { '-i', 'mi' },
    }

    -- 2. Define the Configuration (How to start the session)
    dap.configurations.c = {
      {
        name = 'Debug STM32 (OpenOCD)',
        type = 'gdb',
        request = 'launch',
        -- Path to the elf file generated by your Makefile
        program = function()
          return vim.fn.input('Path to elf: ', vim.fn.getcwd() .. '/build/', 'file')
        end,
        cwd = '${workspaceFolder}',
        stopAtBeginningOfMainSubprogram = true,
        -- This is the "magic" that connects GDB to the hardware
        target = 'localhost:3333',
        setupCommands = {
          {
            text = '-enable-pretty-printing',
            description = 'enable pretty printing',
            ignoreFailures = false,
          },
        },
      },
    }

    vim.keymap.set('n', '<leader>Dl', ':Telescope dap list_breakpoints<CR>', { desc = 'List Breakpoints' })
    vim.keymap.set('n', '<leader>Dv', ':Telescope dap variables<CR>', { desc = 'Search Variables' })

    vim.keymap.set('n', '<leader>Db', dap.toggle_breakpoint, { desc = 'Toggle [B]reakpoint' })
    vim.keymap.set('n', '<leader>Dc', dap.run_to_cursor, { desc = 'Run to [C]ursor' })
    vim.keymap.set('n', '<leader>De', function()
      require('dapui').eval(nil, { enter = true })
    end, { desc = '[E]val variable' })

    vim.keymap.set('n', '<leaderD<F1>', dap.continue, { desc = 'Continue' })
    vim.keymap.set('n', '<leaderD<F2>', dap.step_into, { desc = 'Step into' })
    vim.keymap.set('n', '<leaderD<F3>', dap.step_over, { desc = 'Step over' })
    vim.keymap.set('n', '<leaderD<F4>', dap.step_out, { desc = 'Step out' })
    vim.keymap.set('n', '<leaderD<F5>', dap.step_back, { desc = 'Step back' })
    vim.keymap.set('n', '<leaderD<F0>', dap.restart, { desc = 'Restart' })

    dap.listeners.before.attach.dapui_config = function()
      ui.open()
    end
    dap.listeners.before.launch.dapui_config = function()
      ui.open()
    end
    dap.listeners.before.event_terminated.dapui_config = function()
      ui.close()
    end
    dap.listeners.before.event_exited.dapui_config = function()
      ui.close()
    end
  end,
}
